version: '3.8'

services:
    app:
        image: ghcr.io/suriya-mca/lms
        env_file: .env
        container_name: lms
        ports:
            - "8000:8000"
        volumes:
            - ./app/:/app